/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IModuleData, IModuleDataInterface } from "../IModuleData";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "facetAddress",
                type: "address",
              },
              {
                internalType: "enum IDiamondCut.FacetCutAction",
                name: "action",
                type: "uint8",
              },
              {
                internalType: "bytes4[]",
                name: "functionSelectors",
                type: "bytes4[]",
              },
            ],
            internalType: "struct IDiamondCut.FacetCut[]",
            name: "facetData",
            type: "tuple[]",
          },
          {
            internalType: "bytes32",
            name: "slot",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timeAdded",
            type: "uint256",
          },
          {
            internalType: "string[]",
            name: "facetNames",
            type: "string[]",
          },
        ],
        indexed: false,
        internalType: "struct IModuleData.ModuleData",
        name: "_module",
        type: "tuple",
      },
    ],
    name: "ModuleAdded",
    type: "event",
  },
  {
    inputs: [],
    name: "getActiveModules",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
    ],
    name: "isActiveModule",
    outputs: [
      {
        internalType: "bool",
        name: "exists_",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IModuleData__factory {
  static readonly abi = _abi;
  static createInterface(): IModuleDataInterface {
    return new utils.Interface(_abi) as IModuleDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IModuleData {
    return new Contract(address, _abi, signerOrProvider) as IModuleData;
  }
}
