/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVaultDiamond, IVaultDiamondInterface } from "../IVaultDiamond";

const _abi = [
  {
    inputs: [],
    name: "vaultFactoryDiamond",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vaultOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVaultDiamond__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultDiamondInterface {
    return new utils.Interface(_abi) as IVaultDiamondInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVaultDiamond {
    return new Contract(address, _abi, signerOrProvider) as IVaultDiamond;
  }
}
