/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LibModuleUpgrades,
  LibModuleUpgradesInterface,
} from "../LibModuleUpgrades";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "_moduleName",
        type: "string",
      },
    ],
    name: "VaultDowngraded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "_moduleName",
        type: "string",
      },
    ],
    name: "VaultUpgraded",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122042ce9e464277140c5a399e17501ae1ab8c0edc0a869aa30ebd98cb879f4c33a864736f6c63430008040033";

export class LibModuleUpgrades__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibModuleUpgrades> {
    return super.deploy(overrides || {}) as Promise<LibModuleUpgrades>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibModuleUpgrades {
    return super.attach(address) as LibModuleUpgrades;
  }
  connect(signer: Signer): LibModuleUpgrades__factory {
    return super.connect(signer) as LibModuleUpgrades__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibModuleUpgradesInterface {
    return new utils.Interface(_abi) as LibModuleUpgradesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibModuleUpgrades {
    return new Contract(address, _abi, signerOrProvider) as LibModuleUpgrades;
  }
}
