/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  LibModuleRegistry,
  LibModuleRegistryInterface,
} from "../LibModuleRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "facetAddress",
                type: "address",
              },
              {
                internalType: "enum IDiamondCut.FacetCutAction",
                name: "action",
                type: "uint8",
              },
              {
                internalType: "bytes4[]",
                name: "functionSelectors",
                type: "bytes4[]",
              },
            ],
            internalType: "struct IDiamondCut.FacetCut[]",
            name: "facetData",
            type: "tuple[]",
          },
          {
            internalType: "bytes32",
            name: "slot",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "timeAdded",
            type: "uint256",
          },
          {
            internalType: "string[]",
            name: "facetNames",
            type: "string[]",
          },
        ],
        indexed: false,
        internalType: "struct IModuleData.ModuleData",
        name: "_module",
        type: "tuple",
      },
    ],
    name: "ModuleAdded",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ce474799bb67a547f62eaed4a11193cb0b4417e589fc972779e4d04555f8f78b64736f6c63430008040033";

export class LibModuleRegistry__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<LibModuleRegistry> {
    return super.deploy(overrides || {}) as Promise<LibModuleRegistry>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): LibModuleRegistry {
    return super.attach(address) as LibModuleRegistry;
  }
  connect(signer: Signer): LibModuleRegistry__factory {
    return super.connect(signer) as LibModuleRegistry__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibModuleRegistryInterface {
    return new utils.Interface(_abi) as LibModuleRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibModuleRegistry {
    return new Contract(address, _abi, signerOrProvider) as LibModuleRegistry;
  }
}
