/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ModuleManagerFacetInterface extends ethers.utils.Interface {
  functions: {
    "downgradeVaultWithModule(string)": FunctionFragment;
    "getActiveModules()": FunctionFragment;
    "isActiveModule(string)": FunctionFragment;
    "upgradeVaultWithModule(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "downgradeVaultWithModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveModules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isActiveModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeVaultWithModule",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "downgradeVaultWithModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveModules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActiveModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeVaultWithModule",
    data: BytesLike
  ): Result;

  events: {};
}

export class ModuleManagerFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ModuleManagerFacetInterface;

  functions: {
    downgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getActiveModules(overrides?: CallOverrides): Promise<[string[]]>;

    isActiveModule(
      _name: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { exists_: boolean }>;

    upgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  downgradeVaultWithModule(
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getActiveModules(overrides?: CallOverrides): Promise<string[]>;

  isActiveModule(_name: string, overrides?: CallOverrides): Promise<boolean>;

  upgradeVaultWithModule(
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    downgradeVaultWithModule(
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getActiveModules(overrides?: CallOverrides): Promise<string[]>;

    isActiveModule(_name: string, overrides?: CallOverrides): Promise<boolean>;

    upgradeVaultWithModule(
      _name: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    downgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getActiveModules(overrides?: CallOverrides): Promise<BigNumber>;

    isActiveModule(
      _name: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    downgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getActiveModules(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isActiveModule(
      _name: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeVaultWithModule(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
